### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by lijingrong** [openkoda/openkoda#20]
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'secureEntityDictionaryRepository': Bean with name 'secureEntityDictionaryRepository' has been injected into other beans [modelEnricherInterceptor] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesForType' with the 'allowEagerInit' flag turned off, for example.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:626) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.7.jar!/:6.0.7]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-6.0.7.jar!/:6.0.7]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.7.jar!/:6.0.7]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at com.openkoda.App.startApp(App.java:95) ~[classes!/:1.7.1]
        at com.openkoda.OpenkodaApp.startOpenkodaApp(OpenkodaApp.java:34) ~[classes!/:1.7.1]
        at com.openkoda.OpenkodaApp.main(OpenkodaApp.java:25) ~[classes!/:1.7.1]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[openkoda-1.7.1.jar:1.7.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[openkoda-1.7.1.jar:1.7.1]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[openkoda-1.7.1.jar:1.7.1]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) ~[openkoda-1.7.1.jar:1.7.1]

**Comment by mjbedford** [comment]
I have the same problem, all is good when running in VSCode in either run or debug,  but trying to run from a jar built with the provided pom file I get this error.

**Comment by michalboronski** [comment]
Hi,

Did you use ./target/openkoda-1.7.1.jar ? Because this one is not a Boot fat jar, which is located in ./build/ folder.
Also, make sure to run it using JDK 17

Cheers

**Comment by mabihan** [comment]
I reproduced the problem with these steps : 

1. Build the jar 
```bash
mvn -f openkoda/pom.xml clean install spring-boot:repackage -DskipTests
```

2. Build the image using the jar found in the `build` folder
3. Run the docker compose

```log
 🔍 Look for dynamic entities
2025-05-02T18:22:58.923668389Z  Load database properties for active profile openkoda
2025-05-02T18:22:58.928167199Z  Load database properties for active profile drop_and_init_database
2025-05-02T18:22:58.928541636Z  Load database properties for active profile openkoda
2025-05-02T18:23:01.097107625Z 
2025-05-02T18:23:01.097143970Z   .   ____          _            __ _ _
2025-05-02T18:23:01.097147851Z  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2025-05-02T18:23:01.097150988Z ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2025-05-02T18:23:01.097153841Z  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2025-05-02T18:23:01.097156620Z   '  |____| .__|_| |_|_| |_\__, | / / / /
2025-05-02T18:23:01.097159514Z  =========|_|==============|___/=/_/_/_/
2025-05-02T18:23:01.098640955Z  :: Spring Boot ::                (v3.0.5)
2025-05-02T18:23:01.098671420Z 
2025-05-02T18:23:01.225361051Z 2025-05-02T18:23:01.223Z  INFO 8 --- [           main] com.openkoda.OpenkodaApp                 : Starting OpenkodaApp v1.7.1 using Java 17.0.15 with PID 8 (/app/application.jar started by openkoda-cloud in /app)
2025-05-02T18:23:01.225949288Z 2025-05-02T18:23:01.225Z DEBUG 8 --- [           main] com.openkoda.OpenkodaApp                 : Running with Spring Boot v3.0.5, Spring v6.0.7
2025-05-02T18:23:01.227736086Z 2025-05-02T18:23:01.227Z  INFO 8 --- [           main] com.openkoda.OpenkodaApp                 : The following 2 profiles are active: "openkoda", "drop_and_init_database"
2025-05-02T18:23:03.440770143Z 2025-05-02T18:23:03.440Z  INFO 8 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-05-02T18:23:04.049566609Z 2025-05-02T18:23:04.048Z  INFO 8 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 596 ms. Found 54 JPA repository interfaces.
2025-05-02T18:23:06.519998403Z 2025-05-02T18:23:06.519Z  INFO 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2025-05-02T18:23:06.534983584Z 2025-05-02T18:23:06.534Z  INFO 8 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-05-02T18:23:06.535255944Z 2025-05-02T18:23:06.534Z  INFO 8 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.7]
2025-05-02T18:23:06.652451661Z 2025-05-02T18:23:06.651Z  INFO 8 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-05-02T18:23:06.653351160Z 2025-05-02T18:23:06.652Z  INFO 8 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4867 ms
2025-05-02T18:23:06.995464773Z 2025-05-02T18:23:06.992Z  INFO 8 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2025-05-02T18:23:07.087146872Z 2025-05-02T18:23:07.086Z  INFO 8 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.1.7.Final
2025-05-02T18:23:07.446130791Z 2025-05-02T18:23:07.445Z  INFO 8 --- [           main] o.h.spatial.integration.SpatialService   : HHH80000001: hibernate-spatial integration enabled : true
2025-05-02T18:23:07.778840747Z 2025-05-02T18:23:07.778Z  INFO 8 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-05-02T18:23:07.861980506Z 

...
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2025-05-02T18:23:23.425261048Z 2025-05-02T18:23:23.419Z ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application run failed
2025-05-02T18:23:23.425287452Z 
2025-05-02T18:23:23.425293872Z org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'secureEntityDictionaryRepository': Bean with name 'secureEntityDictionaryRepository' has been injected into other beans [modelEnricherInterceptor] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesForType' with the 'allowEagerInit' flag turned off, for example.
2025-05-02T18:23:23.425302585Z 
```
