### ISSUE TITLE
register login report 404 403 error 

### ISSUE THREAD

**Issue by heming79** [openkoda/openkoda#9]
2024-05-31T06:13:21.834Z DEBUG 808 --- [nio-8080-exec-8] c.o.core.multitenancy.QueryExecutor      : 20240531061321-0KLX0g5B: [runEntityManagerOperationForOrg] org null t true
2024-05-31T06:13:21.835Z DEBUG 808 --- [nio-8080-exec-8] c.o.core.multitenancy.QueryExecutor      : 20240531061321-0KLX0g5B: [runEntityManagerOperationForOrg] search path "$user", public tr org=null, host='null', entityKey='null', method='null', pre=-1}
2024-05-31T06:13:21.864Z DEBUG 808 --- [nio-8080-exec-7] s.s.w.f.HttpStatusRequestRejectedHandler : Rejecting request due to: The request was rejected because the URL contained a potentially malicious String ";"

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
        at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:535) ~[spring-security-web-6.0.2.jar!/:6.0.2]
        at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:505) ~[spring-security-web-6.0.2.jar!/:6.0.2]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-6.0.2.jar!/:6.0.2]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.0.2.jar!/:6.0.2]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.7.jar!/:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.7.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2024-05-31T06:13:21.866Z DEBUG 808 --- [nio-8080-exec-7] o.s.security.web.FilterChainProxy        : Securing GET /error?v=2405310609
2024-05-31T06:13:21.867Z DEBUG 808 --- [nio-8080-exec-7] o.s.s.w.u.matcher.RegexRequestMatcher    : Checking match of request : '/error?v=2405310609'; against '/[0-9a-zA-Z\-\/]*\@?(?:\.css|\.js|\.xml|\.txt|\.csv|\.json|\.html)?(?:\?organizationId=?.*)?'
2024-05-31T06:13:21.867Z DEBUG 808 --- [nio-8080-exec-7] o.s.s.w.u.matcher.RegexRequestMatcher    : Checking match of request : '/error?v=2405310609'; against '/[0-9a-zA-Z\-\/]*\@?(?:\.css|\.js|\.xml|\.txt|\.csv|\.json|\.html)?(\?(.*=?.*)?(\&.*=?.*)?)?'
2024-05-31T06:13:21.867Z DEBUG 808 --- [nio-8080-exec-7] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2024-05-31T06:13:21.868Z DEBUG 808 --- [nio-8080-exec-7] o.s.s.w.s.HttpSessionRequestCache        : Saved request http://172.16.106.119:8080/error?v=2405310609&continue to session
2024-05-31T06:13:21.868Z DEBUG 808 --- [nio-8080-exec-7] o.s.s.w.a.Http403ForbiddenEntryPoint     : Pre-authenticated entry point called. Rejecting access

**Comment by heming79** [comment]
![image](https://github.com/openkoda/openkoda/assets/14069019/bd3eb70f-1219-4db9-96fd-facb0d66fa59)

**Comment by lukas-beumer** [comment]
Same here, seems to be an error with the csrf token

**Comment by arekdrysch** [comment]
Thanks, queuing this for replication.

**Comment by lukas-beumer** [comment]
Any news on this? It's not usable right now.

**Comment by arekdrysch** [comment]
A fix for thi issue will come with a next release scheduled for the next week (16 July)

**Comment by arekdrysch** [comment]
Thank you for your patience. 
The issue was caused due to strict secure cookies setting in Openkoda. 
It occurs when both conditions are met:
* an instance is accessed via http, and
* the host in URL in the browser is other than "localhost" (or 127.0.0.1)
When the scenarios are met, then the session cookie is lost and CRSF tokens can't be matched with the session.

This behavior is generally correct as it increases security.

There is a new flag (environment variable) in the docker image:
`SECURE_COOKIE` (default `true`)

In order to resolve the issue for http communication over the local network:
* Set the `SECURE_COOKIE` environment variable to `false` before starting docker compose, eg. `SET SECURE_COOKIE=false` (windows), `SECURE_COOKIE=false` (linux)
* You may need to delete your locally cached Openkoda docker images with `docker rmi`
* Then proceed as described here: https://github.com/openkoda/openkoda?tab=readme-ov-file#docker-compose
